# docker-compose configuration file for lead-alerts-node
web:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/src/app
  environment:
    - TWILIO_ACCOUNT_SID
    - TWILIO_AUTH_TOKEN
    - TWILIO_NUMBER
    - AGENT_NUMBER
